name: certificate_pinning_httpclient
description: An implementation of Dart's HttpClient with certificate pinning against SPKI hashes.
version: 0.0.2
repository: https://github.com/sebkoller/certificate_pinning_httpclient

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  asn1lib: ^1.6.4
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  logger: ^2.5.0
  pem: ^2.0.5

dev_dependencies:
  lint: ^2.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dev.koller.certificate_pinning_httpclient
        pluginClass: CertificatePinningHttpClientPlugin
      ios:
        pluginClass: CertificatePinningHttpClientPlugin
